### ISSUE TITLE
cannot compile with `-haddock` with ghc-8.10

### ISSUE THREAD

**Issue by jwaldmann** [haskell-hvr/cabal-plan#81]
I have `ghc-options: -haddock` in my (global) cabal config. With ghc-8.10.7, this happens:
```
cabal install cabal-plan
...
[6 of 6] Compiling Main             ( src-exe/cabal-plan.hs, dist/build/cabal-plan/cabal-plan-tmp/Main.o )

src-exe/cabal-plan.hs:155:5: error:
    parse error on input ‘-- $ cabal-plan list-bin cab<TAB>’
    |
155 |     -- $ cabal-plan list-bin cab<TAB>
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build exe:cabal-plan from cabal-plan-0.7.2.1. See the build
log above for details.
```
The fix is trivial (I can send patch). Perhaps it's not even needed, since it's fine with ghc-9.

**Comment by phadej** [comment]
Fixed in #86
